---
title: "Titanic"
author: "Dongdong Zhang"
date: "11/06/2018"
output: html_document
---

```{r}
# library
library(ggplot2)
library(ggthemes)
library(scales)
library(plyr)
library(dplyr)
library(mice)
library(randomForest)
library(party)
library(corrplot)

```


```{r}
train = read.csv("/Users/allenzhang/Desktop/kaggle_data_set/Titanic/train.csv")
test = read.csv("/Users/allenzhang/Desktop/kaggle_data_set/Titanic/test.csv")
```

```{r}
str(train)
str(test)
data <- bind_rows(train,test)
summary(data)
```

```{r}
sapply(data,function(x) sum(is.na(x)))
sapply(data,function(x) sum(x == ""))
```


```{r}
Embarked.na <- data$Embarked
which(Embarked.na %in% "")
```

```{r}
data_62 <- data[data$PassengerId == 62,]
data_830 <- data[data$PassengerId == 830,]
data_62
data_830
```

```{r}
ggplot(data[!is.na(data$Embarked),],aes(x=Embarked, y=Fare, fill=factor(Pclass))) +
  geom_boxplot() + 
  geom_hline(aes(yintercept=80), color='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format())

```


```{r}
data$Embarked[c(62,830)] <- "C"
sapply(data,function(x) sum(x == ""))
```


```{r}
Fare.na = is.na(data$Fare)
which(Fare.na %in% TRUE)
```


```{r}
data_1044 = data[data$PassengerId == 1044,]
data_1044
```


```{r}
ggplot(data[data$Embarked=='S' & data$Pclass == 3,],aes(x=Embarked, y=Fare, fill=factor(Pclass))) +
  geom_boxplot() + 
  geom_hline(aes(yintercept=80), color='red', linetype='dashed', lwd=2) +
  scale_y_continuous(labels=dollar_format())
```

```{r}
b = median(data$Fare[data$Embarked == 'S' & data$Pclass ==3], na.rm = T)

```


```{r}
data$Fare[1044] = 8.05
sapply(data, function(x) sum(is.na(x)))
```

```{r}
data[is.na(data$Age),]
```


```{r}
set.seed(129)

ss <- c('PassengerId','Name','Ticket','Cabin','family','Surname','Survived')
mice_age <- mice(data[,!names(data) %in% ss],method = 'rf')
mice_output <- complete(mice_age)

```

```{r}

par(mfrow=c(1,2))
hist(data$Age,freq = F,main = 'Age:ORiginal Data',col='darkblue',ylim = c(0,0.04))
hist(mice_output$Age,freq = F,main = 'Age:MICE Output',col = 'skyblue',ylim = c(0,0.04))


```

```{r}
data$Age <- mice_output$Age

```

```{r}
sapply(data,function(x) sum(is.na(x)))
sapply(data,function(x) sum(x == ""))
summary(data)
```


### Analysis

#### Pclass
```{r}

data$Survived <- factor(data$Survived)
ggplot(data = data[1:nrow(train),], mapping = aes(x = Pclass, y = ..count.., fill=Survived)) + 
  geom_bar(stat = "count", position='dodge') + 
  xlab('Pclass') + 
  ylab('Count') + 
  ggtitle('Different Pclass impact survived') + 
  scale_fill_manual(values=c("#FF0000", "#00FF00")) +
  geom_text(stat = "count", aes(label = ..count..), position=position_dodge(width=1), , vjust=-0.5) + 
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")
```

#### Name Title
```{r}
data$Title <- sapply(data$Name, FUN=function(x) {strsplit(x, split='[,.]')[[1]][2]})
data$Title <- sub(" ","",data$Title)
table(data$Title)               

```

```{r}
Others <- c('Capt','Col','Don','Dona','Jonkheer','Lady','Major','Sir','the Countess')
data$Title[data$Title=='Mlle'] <- 'Miss'
data$Title[data$Title=='Mme'] <- 'Mrs'
data$Title[data$Title=='Ms'] <- 'Miss'
data$Title[data$Title %in% Others] <- 'Others'
table(data$Title)

```

```{r}
ggplot(data = data[1:891,], mapping = aes(x = Title, y = ..count.., fill=Survived)) + 
  geom_bar(stat = "count", position='stack') + 
  xlab('Title') + 
  ylab('Count') + 
  ggtitle('Different Title impact survivor') + 
  scale_fill_discrete(name="Survived", breaks=c(0, 1), labels=c("0", "1")) + 
  geom_text(stat = "count", aes(label = ..count..), position=position_stack(vjust = 0.5)) +
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")

```
#### sex
```{r}
data$Sex <- as.factor(data$Sex)
ggplot(data = data[1:891,], mapping = aes(x = Sex, y = ..count.., fill=Survived)) + 
  geom_bar(stat = 'count', position='dodge') + 
  xlab('Sex') + 
  ylab('Count') + 
  ggtitle('Different Sex impact survivor') + 
  geom_text(stat = "count", aes(label = ..count..), position=position_dodge(width=1), , vjust=-0.5) + 
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")
```

#### Family Size
```{r}
#### SibSp
ggplot(data = data[1:891,], mapping = aes(x = SibSp, y = ..count.., fill=Survived)) + 
  geom_bar(stat = 'count', position='dodge') + 
  labs(title = "Different SibSp impact survivor", x = "Sibsp", y = "Count", fill = "Survived") + 
  geom_text(stat = "count", aes(label = ..count..), position=position_dodge(width=1), , vjust=-0.5) +
  scale_x_continuous(breaks = c(0:8)) +
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")
#### Parch
ggplot(data = data[1:891,], mapping = aes(x = Parch, y = ..count.., fill=Survived)) + 
  geom_bar(stat = 'count', position='dodge') + 
  labs(title = "Different Parch impact survivor", x = "Parch", y = "Count", fill = "Survived") + 
  geom_text(stat = "count", aes(label = ..count..), position=position_dodge(width=1), , vjust=-0.5) + 
  scale_x_continuous(breaks = c(0:6)) +
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")
```

```{r}
data$FamilySize <- data$SibSp + data$Parch + 1
data$FamilySize
```


```{r}

ggplot(data = data[1:891,], mapping = aes(x = FamilySize, y = ..count.., fill=Survived)) + 
  geom_bar(stat = 'count', position='dodge') + 
  xlab('FamilySize') + 
  ylab('Count') + 
  ggtitle('Different FamilySize impact survivor') + 
  geom_text(stat = "count", aes(label = ..count..), position=position_dodge(width=1), , vjust=-0.5) + 
  scale_x_continuous(breaks = c(0:11)) +
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")
```

#### Age
```{r}
ggplot(data[!is.na(data$Survived),],aes(Age,color=Survived))+
 geom_bar(stat = 'count', position='dodge') + 
  xlab('Age') + 
  ylab('Count') + 
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")

```


```{r}
data$Age_New[data$Age < 18] <- 'child'
data$Age_New[data$Age >= 18] <- 'adult'
# data$Age_New
table(data$Age_New,data$Survived)
```

```{r}
ggplot(data[!is.na(data$Survived),],aes(Age_New,fill=Survived))+
  geom_bar(stat = 'count',position = 'dodge')+
  ggtitle('Adult and Child  Impact Survivor')+
  geom_text(stat = "count", aes(label = ..count..), position=position_dodge(width=1), , vjust=-0.5) + 
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")

```
#### Ticket
```{r}
ticket.count <- aggregate(data$Ticket, by = list(data$Ticket), function(x) sum(!is.na(x)))
ticket.count
table(ticket.count$x)
```

#### Fare
```{r}
ggplot(data = data[!is.na(data$Survived) ,], aes(x = Fare, color=Survived)) + 
  geom_line(aes(label=..count..), stat = 'bin', binwidth=10)  + 
  labs(title = "Different Fare impact survivor", x = "Fare", y = "Count", fill = "Survived")+
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")

```

#### Embarked
```{r}
ggplot(data[1:891, ], mapping = aes(x = Embarked, y = ..count.., fill = Survived)) +
  geom_bar(stat = 'count', position='dodge') + 
  xlab('Embarked') +
  ylab('Count') +
  ggtitle('Different Embarked impact survivor') +
  geom_text(stat = "count", aes(label = ..count..), position=position_dodge(width=1), , vjust=-0.5) + 
  theme(plot.title = element_text(hjust = 0.5), legend.position="bottom")
```


### Predict
```{r}
data$Pclass <- factor(data$Pclass)
data$Title <- factor(data$Title)
data$Sex <- factor(data$Sex)
data$Age_New <- factor(data$Age_New)
data$FamilySize <- factor(data$FamilySize)
data$Fare <- factor(data$Fare)
data$Embarked <- factor(data$Embarked)
train <- data[1:891,]
test <- data[892:1309,]

model <- cforest(Survived ~ Pclass + Title + Sex + Age_New + FamilySize + Fare + Embarked, data = train,controls = cforest_unbiased(ntree=2000,mtry=3))

```

```{r}
prediction<-predict(model,newdata = test,OOB=TRUE,type = "response") 
output<-data.frame(PassengerId=test$PassengerId,Survived=prediction)
output
write.csv(output,file = "/Users/allenzhang/Desktop/kaggle_data_set/Titanic/res.csv",row.names = FALSE)
```


